### ISSUE TITLE
How can I print a bigger text?

### ISSUE THREAD

**Issue by thiagopeluque** [BrooonS/react-native-bluetooth-escpos-printer#3]
I need to print a price tag with various information, but the price needs to be in a larger font. Is there such a possibility?
Below are images of what I have and what I need to achieve

My code
`async function printVerticalLabel() {
    try {
      await BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.CENTER);
      await BluetoothEscposPrinter.setBlob(1);
      await BluetoothEscposPrinter.printText(produto.descricao.substring(0, 30)+"\n\r", {});
      await BluetoothEscposPrinter.setBlob(0);
      await BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.CENTER);
      await BluetoothEscposPrinter.printText("Cod: " + produto.codigo + "   Un: " + produto.unid_medida + "\n\r", {});
      await BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.CENTER);
      await BluetoothEscposPrinter.printText("Fabricante: " + produto.fabricante + "\n\r", {});
      await BluetoothEscposPrinter.printText(produto.preco_venda.toFixed(2) + "\n\r",{
        encoding:'Windows-1252',
        codepage:0,
        widthtimes:2,
        heigthtimes:2,
        fonttype:1
      });
      await BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.CENTER);
      await BluetoothEscposPrinter.printBarCode(produto.codigo_barras, BluetoothEscposPrinter.BARCODETYPE.JAN13, 3, 60, 0, 2);
      await BluetoothEscposPrinter.printText("\r\n\r\n\r\n", {});
    } catch {
      const value = await AsyncStorage.getItem('address');
      if (value !== null) {
        ToastAndroid.show(
          'Estou conectado porém a impressora está desligada',
          ToastAndroid.LONG,
          ToastAndroid.BOTTOM,
        );
      } else {
        ToastAndroid.show(
          'Você ainda não se conectou com uma impressora',
          ToastAndroid.LONG,
          ToastAndroid.BOTTOM,
        );
      }
    }
    
  }`

**Left side:** What I have so far
**Right side:** What I need to achieve

![image](https://github.com/user-attachments/assets/9ae3af5b-8a22-42a2-aea7-1d12bfca302f)

**Comment by letstri** [comment]
I'm not sure but you can try fonttype and scale in text property
